server.port=8080
spring.main.allow-bean-definition-overriding=true

# =========================================================
# Database - Primary (writes)
# =========================================================
app.datasource.primary.url=jdbc:postgresql://db-primary:5432/cap_db
app.datasource.primary.username=root
app.datasource.primary.password=root
app.datasource.primary.driver-class-name=org.postgresql.Driver

# =========================================================
# Database - Replica (reads)
# =========================================================
app.datasource.replica.url=jdbc:postgresql://db-replica:5432/cap_db
app.datasource.replica.username=root
app.datasource.replica.password=root
app.datasource.replica.driver-class-name=org.postgresql.Driver

# =========================================================
# JPA / Hibernate
# =========================================================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update