apiVersion: apps/v1
kind: Deployment
metadata:
  name: cap-availability

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cap-availability

  template:
    metadata:
      labels:
        app: cap-availability
    spec:
      containers:
        - name: cap-availability
          image: cap-availability-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
