apiVersion: apps/v1
kind: Deployment
metadata:
  name: cap-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cap-api

  template:
    metadata:
      labels:
        app: cap-api
    spec:
      containers:
        - name: cap-api
          image: cap-api:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 718Mi

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cap-api

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cap-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
#    - type: Resource
#      resource:
#        name: memory
#        target:
#          type: Utilization
#          averageUtilization: 70

---

apiVersion: v1
kind: Service
metadata:
  name: cap-api
  labels:
    name: cap-api

spec:
  type: LoadBalancer

  selector:
    app: cap-api
  ports:
    - port: 8080
      targetPort: 8080

#---

#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: cap-availability
#
#spec:
#  rules:
#    - host: cap-availability.local
#
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#
#            backend:
#              service:
#                name: cap-availability
#                port:
#                  number: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1

  selector:
    matchLabels:
      app: db

  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: root
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_DB
              value: cap_db
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi

---

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    app: db

  ports:
    - port: 5432
      targetPort: 5432
