apiVersion: v1
kind: Pod
metadata:
  name: cap-availability
  labels:
    app: cap-availability

spec:
  containers:
  - name: cap-availability
    image: cap-availability-app:v1
    ports:
      - containerPort: 8080